In [1]:
# Loading the dataset using pandas

import pandas as pd

df = pd.read_csv('loan_approval.csv')

In [2]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self Employed,Applicant Income,Coapplicant Income,Loan Amount,Loan Term,Credit History,Property Area,Loan Approval
0,LP001002,Male,No,0,Graduate,No,5849,0,110.0,360,1,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.0,360,1,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360,1,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360,1,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360,1,Urban,Y

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loan_ID             614 non-null    object
 1   Gender              614 non-null    object
 2   Married             614 non-null    object
 3   Dependents          614 non-null    object
 4   Education           614 non-null    object
 5   Self Employed       614 non-null    object
 6   Applicant Income    614 non-null    int64
 7   Coapplicant Income  614 non-null    int64
 8   Loan Amount         606 non-null    float64
 9   Loan Term           614 non-null    int64
 10  Credit History      614 non-null    int64
 11  Property Area       614 non-null    object
 12  Loan Approval       614 non-null    object
dtypes: float64(1), int64(4), object(8)
memory usage: 62.5+ KB

In [4]:
df.describe(include = 'all')

,Loan_ID,Gender,Married,Dependents,Education,Self Employed,Applicant Income,Coapplicant Income,Loan Amount,Loan Term,Credit History,Property Area,Loan Approval
count,614,614,614,614,614,614,614.000000,614.000000,606.000000,614.000000,614.000000,614,614
unique,614,2,2,4,2,2,NaN,NaN,NaN,NaN,NaN,3,2
top,LP001002,Male,Yes,0,Graduate,No,NaN,NaN,NaN,NaN,NaN,Semiurban,Y
freq,1,497,398,352,480,523,NaN,NaN,NaN,NaN,NaN,233,422
mean,NaN,NaN,NaN,NaN,NaN,NaN,5403.459283,1661.921824,146.798680,341.726384,0.827362,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,6109.041673,3001.663815,86.304012,64.738526,0.378243,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,0.000000,9.000000,12.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2877.500000,0.000000,100.000000,360.000000,1.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,3812.500000,1221.000000,127.000000,360.000000,1.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,5795.000000,2324.000000,168.000000,360.000000,1.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,81000.000000,41667.000000,700.000000,480.000000,1.000000,NaN,NaN

In [5]:
# Checking if missing data or null values are present in the dataset

df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self Employed         0
Applicant Income      0
Coapplicant Income    0
Loan Amount           8
Loan Term             0
Credit History        0
Property Area         0
Loan Approval         0
dtype: int64

In [7]:
df['Loan Amount'] = df.groupby('Loan Term')['Loan Term'].transform(lambda x : x.fillna(x.median()))

In [8]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self Employed         0
Applicant Income      0
Coapplicant Income    0
Loan Amount           0
Loan Term             0
Credit History        0
Property Area         0
Loan Approval         0
dtype: int64

In [9]:
# Renaming columns according to snake casing for better readability and documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [10]:
df.columns

Index(['loan_id', 'gender', 'married', 'dependents', 'education',
       'self_employed', 'applicant_income', 'coapplicant_income',
       'loan_amount', 'loan_term', 'credit_history', 'property_area',
       'loan_approval'],
      dtype='object')

In [16]:
label_map = {
    '0': 'Single',
    '1': 'Couple',
    '2': 'Couple with a kid',
    '3+': 'Family'
}

df['family_size'] = df['dependents'].map(label_map)

In [18]:
df['family_size'].head(20)

0                Single
1                Couple
2                Single
3                Single
4                Single
5     Couple with a kid
6                Single
7                Family
8     Couple with a kid
9                Couple
10    Couple with a kid
11    Couple with a kid
12    Couple with a kid
13               Single
14    Couple with a kid
15               Single
16               Couple
17               Single
18               Single
19               Single
Name: family_size, dtype: object

In [19]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in C:\Users\seerv\anaconda3\Lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in C:\Users\seerv\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\seerv\anaconda3\Lib\site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\seerv\anaconda3\Lib\site-packages (from sqlalchemy) (4.15.0)

WARNING: Ignoring invalid distribution ~umpy (C:\Users\seerv\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\seerv\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\seerv\anaconda3\Lib\site-packages)

In [21]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# MySQL connection
username = "root"
password = quote_plus("Chigsa@01")
host = "localhost"
port = "3306"
database = "loan_approval"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "loan"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM loan LIMIT 5;", engine)

,loan_id,gender,married,dependents,education,self_employed,applicant_income,coapplicant_income,loan_amount,loan_term,credit_history,property_area,loan_approval,family_size
0,LP001002,Male,No,0,Graduate,No,5849,0,360,360,1,Urban,Y,Single
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,360,360,1,Rural,N,Couple
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,360,360,1,Urban,Y,Single
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,360,360,1,Urban,Y,Single
4,LP001008,Male,No,0,Graduate,No,6000,0,360,360,1,Urban,Y,Single